name: pr-title
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
permissions: {}
jobs:
  lint:
    permissions:
      pull-requests: read
    uses: ianmkinney/Ian-tool-belt/.github/workflows/pr-title-reusable.yml@__BELT_SHA__ # v__BELT_VERSION__
