"""Generate styling/tokens.css from styling/tokens.json."""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOKENS = ROOT / 'styling/tokens.json'
CSS = ROOT / 'styling/tokens.css'
GROUPS = ('color', 'font', 'radius', 'shadow', 'focus')


def render(tokens):
    lines = ['/* Generated by scripts/build_tokens.py from tokens.json. Do not edit. */', ':root {']
    for group in GROUPS:
        for name, value in tokens[group].items():
            lines.append(f'  --tb-{group}-{name}: {value};')
    lines.append('}')
    return '\n'.join(lines) + '\n'


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='fail if tokens.css is out of date')
    args = parser.parse_args(argv)
    css = render(json.loads(TOKENS.read_text()))
    if args.check:
        if not CSS.exists() or CSS.read_text() != css:
            print('styling/tokens.css is out of date; run python3 scripts/build_tokens.py', file=sys.stderr)
            return 1
        print('styling/tokens.css is up to date')
        return 0
    CSS.write_text(css)
    print(f'Wrote {CSS.relative_to(ROOT)}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
