name: pr-title
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
permissions: {}
jobs:
  lint:
    permissions:
      pull-requests: read
    uses: $/.github/workflows/pr-title-reusable.yml
